Repository belf-kr/api-gateway, pull requests merged in 2021-11, with the labels that each got.

#57 up: wokr-todo 생성시 필수 입력값에 대한 HTTP 양식 추가
  src/todo/todo.http
Labels: documentation

#58 up: work done 테이블 값을 리스트로 가져오는 API endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature

#59 up: DB 스키마 변경
  src/common/type/work-todo.type.ts
  src/todo/todo.http
Labels: modify

#60 up: work_todo 생성 시 activeDate 입력 위한 API 폼 추가
  src/todo/todo.http
Labels: documentation

#61 up: type 관련 코드 세분화
  src/common/type/course-get.interface.ts
  src/common/type/course-post.interface.ts
  src/common/type/course.type.ts
  src/common/type/work-todo-get.interface.ts
  src/common/type/work-todo-post.interface.ts
  src/common/type/work-todo.type.ts
  src/todo/todo.controller.ts
Labels: modify

#62 up: work todo 생성 시 반복 요일 정보 입력 가능하게 기능 수정
  package-lock.json
  package.json
  src/common/type/work-todo-post.interface.ts
  src/todo/todo.http
Labels: modify

#64 JS 모듈을 import 하는 코드를 권장 방법으로 수정
  src/app.module.ts
Labels: modify

#65 oauth-service Middleware 삭제 및 k8s 스케줄러 최적화
  .env.dev
  README.md
  k8s/prod.yaml
  k8s/qa.yaml
  package-lock.json
  package.json
  src/app.module.ts
  src/middleware/middleware.module.ts
  src/middleware/oauth.middleware.ts
Labels: bug

#66 v0.4.1
  .env.dev
  README.md
  k8s/prod.yaml
  k8s/qa.yaml
  package-lock.json
  package.json
  src/app.module.ts
  src/middleware/middleware.module.ts
  src/middleware/oauth.middleware.ts
Labels: bug, k8s

#68 v0.4.2
  k8s/prod.yaml
  k8s/qa.yaml
  package-lock.json
  package.json
Labels: k8s

#71 한일을 POST 요청할 시 JWT 토큰에서 유저 ID 값을 가져오도록 수정
  src/middleware/middleware.module.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: modify

#72 work_todo 입력 시 courseId 값을 JWT에서 입력기능 추가
  src/common/type/work-todo.type.ts
  src/middleware/middleware.module.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature, modify

#73 Get, Delete 요청시 userId를 JWT에서 가져와 요청하는 기능 추가
  src/middleware/middleware.module.ts
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature, modify

#74 반복 일수에 따라 반복되는 work-todo 리스트 가져오는 API endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature, modify

#75 Get 요청시 JWT 인증 삭제
  src/middleware/middleware.module.ts
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: modify

#76 Course 조회시 userId 필터 기능 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature, modify

#77 course Id 사용해 단일 course 가져오는 API Endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature, modify

#80 Color 생성 기능 API endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature

#81 course creatorId 컬럼명 변경에 따른 API 코드 변경
  src/common/type/course.type.ts
  src/todo/todo.service.ts
Labels: modify

#84 파일 추가시 userId 입력기능 추가
  src/middleware/middleware.module.ts
  src/storage/lib/api.ts
  src/storage/storage.controller.ts
  src/storage/storage.module.ts
  src/storage/storage.service.ts
Labels: new feature

#85 File 삭제하는 API endpoint 추가
  src/middleware/middleware.module.ts
  src/storage/lib/api.ts
  src/storage/storage.controller.ts
  src/storage/storage.http
  src/storage/storage.service.ts
Labels: new feature

#86 Storage service 기본 listen port 변경
  .vscode/launch.json
  README.md
  k8s/prod.yaml
  k8s/qa.yaml
  package-lock.json
  package.json
  src/app.module.ts
  src/storage/storage.http
Labels: documentation, modify

#88 서비스 로직 처리 시간 로깅 기능 추가
  src/app.module.ts
  src/interceptor/logging.interceptor.ts
Labels: new feature

#89 개발환경 구축 및 실행환경 README.md만 보고 구축 가능하게 수정
  README.md
Labels: documentation

#90 스케일 업 및 k8s 헬스 체크 추가
  k8s/prod.yaml
  k8s/qa.yaml
Labels: k8s

#91 로컬 개발용 docker파일 추가
  docker-compose.yml
  package.json
  src/common/lib/service.ts
Labels: new feature

#92 work todo 1개 가져오는 API endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature

#93 work-todo 조회시 courseId 가져올 수 있게 타입코드 수정
  src/common/type/work-todo-get.interface.ts
Labels: new feature
