Repository belf-kr/api-gateway, pull requests merged in 2021-12, with the labels that each got.

#97 JWT 입력값 형식 변경
  src/belf-jwt/belf-jwt.service.ts
  src/middleware/oauth.middleware.ts
  src/todo/todo.http
Labels: modify

#98 Docker 사용해 개발 환경에서 즉시 실행법 설명 추가
  README.md
Labels: documentation

#96 storage service 관련 코드 삭제
  src/app.module.ts
  src/middleware/middleware.module.ts
  src/storage/lib/api.ts
  src/storage/storage.controller.ts
  src/storage/storage.http
  src/storage/storage.module.ts
  src/storage/storage.service.ts
Labels: modify

#99 정상적으로 한일을 가져올 수 있도록 쿼리스트링 로직 픽스
  src/todo/lib/api.ts
Labels: bug

#100 버전 정보 업데이트
  .gitignore
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
Labels: documentation

#102 nodeenv 정의 및 설치 방법 추가
  README.md
Labels: documentation

#103 course import 관련 http 양식 추가
  src/todo/todo.http
Labels: documentation

#104 API 코드 내 querystring 처리 로직 수정
  src/todo/lib/api.ts
  src/todo/todo.http
Labels: bug, documentation

#108 course 제목 검색 기능 API endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature

#109 course 조회시 userEmail 반환 양식 추가
  src/common/type/course-get.interface.ts
Labels: new feature

#110 import된 course만 가져오는 API endpoint 추가
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature

#111 deprecated된 kubectl 명령어 변경, slack slack notification 메시지 표시되도록
  .github/workflows/aks-prod-deploy.yaml
  .github/workflows/aks-qa-deploy.yaml
  .github/workflows/aks-test-deploy.yaml
  package-lock.json
  package.json
  src/app.controller.ts
Labels: bug, modify, k8s

#113 유저 탈퇴시 데이터 삭제 API endpoint 추가
  src/middleware/middleware.module.ts
  src/todo/lib/api.ts
  src/todo/todo.controller.ts
  src/todo/todo.http
  src/todo/todo.service.ts
Labels: new feature
